### ISSUE TITLE
Question about the script.

### ISSUE THREAD

**Issue by MikkelDK** [F-He/Discord_Bot_For_LGSM#7]
Hi, @F-He 

I would like to hear, about it's possible to share "BOT" between discord servers, so **user** can control their own gameserver, or do I need to host "each separate bot"?

And, will it work for CSGO Server too?

Regards
Mikkel

**Comment by F-He** [comment]
You can run the bot on multiple discord servers, but only on 1 Linux instance.

**Comment by MikkelDK** [comment]
Hi @F-He 

Is there planned for, it will support the second method of Linux instance?

As example:
```
[game_servers]
; Specify here which game servers the bot should manage.
; The value on the left represents the corresponding Linux User
; and the value on the right represents the path to the server file.
mrc4t = /home/fsh/mrc4t
test = /home/fsh/test
```
So it's possible to make it work, so I can use: !start mrc4t, without it's a "user" but just "alias" > so it can start from user: "fsh"?
I'm willing to pay if it's possible to make it work on my request =D
